# Generated by Django 3.1.2 on 2020-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.IntegerField(choices=[(3, 'Choose many'), (1, 'By text'), (2, 'Choose one')]),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choices', to='polls_api.AnswerChoice'),
        ),
    ]
